CREATE DATABASE db_personagem;

USE db_personagem;

CREATE TABLE classe(

id BIGINT auto_increment,
Classe VARCHAR(50),
PRIMARY KEY (id)

);
INSERT INTO classe (Classe)VALUES("Suporte"); -- 1
INSERT INTO classes (Classe)VALUES("Tanke"); -- 2 
INSERT INTO classes (Classe)VALUES("Flanco"); -- 3
INSERT INTO Classes (Classe)VALUES("Dano");

SELECT * FROM classe;
CREATE TABLE HAB.SUPORTE1(
id BIGINT auto_increment,
Habilidade1 VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO HAB.SUPORTE1(Habilidade1)VALUES("");

CREATE TABLE HAB.SUPORTE2(
id BIGINT auto_increment,
Habilidade2 VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO HAB.SUPORTE2(Habilidade2)VALUES("");


CREATE TABLE HAB.SUPORTE3(
id BIGINT auto_increment,
Habilidade3 VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO HAB.SUPORTE3(Habilidade3)VALUES("");

CREATE TABLE PASSIVA.SUPORTE(
id BIGINT auto_increment,
Passiva VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO PASSIVA.SUPORTE(Passiva)VALUES("");

CREATE TABLE SUPREMA.SUPORTE(
id BIGINT auto_increment,
Suprema VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO SUPREMA.SUPORTE(Suprema)VALUES("");

CREATE TABLE HAB.TANK1(
id BIGINT auto_increment,
Habilidade1 VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO HAB.TANK1(Habilidade1)VALUES("");

CREATE TABLE HAB.TANK2(
id BIGINT auto_increment,
Habilidade2 VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO HAB.TANK2(Habilidade2)VALUES("");

CREATE TABLE HAB.TANK3(
id BIGINT auto_increment,
Habilidade3 VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO HAB.TANK1(Habilidade3)VALUES("");

CREATE TABLE PASSIVA.TANK(
id BIGINT auto_increment,
Passiva VARCHAR(255),
PRIMARY KEY(id)
);
INSERT INTO PASSIVA.TANK(Passiva)VALUES("");
CREATE TABLE SUPREMA.TANK(
id BIGINT auto_increment,
Suprema VARCHAR(255),
PRIMARY KEY(id)
);

INSERT INTO PASSIVA.SUPREMA(Suprema)VALUES("");

CREATE TABLE HAB.DANO1();
CREATE TABLE HAB.DANO2();
CREATE TABLE HAB.DANO3();
CREATE TABLE PASSIVA.DANO();
CREATE TABLE SUPREMA.DANO();

CREATE TABLE HAB.FLANK1();
CREATE TABLE HAB.FLANK2();
CREATE TABLE HAB.FLANK3();
CREATE TABLE PASSIVA.FLANK();
CREATE TABLE SUPREMA.FLANK();

CREATE TABLE PERSONAGEM(

id BIGINT auto_increment,
NOME VARCHAR(255),
CLASSE BIGINT,
HABILIDADE1 BIGINT,
HABILIDADE2 BIGINT,
HABILIDADE3 BIGINT,
PASSIVA BIGINT,
SUPREMA BIGINT,
PRIMARY KEY (id),
FOREIGN KEY (CLASSE) REFERENCES classe(id),
FOREIGN KEY () REFERENCES 
);


